manifest:
  defaults:
    remote: akkfork
    revision: freeze/spi_target_base  # frozen branch for spi changes

  remotes:
    - name: akkfork
      url-base: https://github.com/akkhauv

  projects:
    - name: zephyr
      remote: akkfork
      revision: freeze/spi_target_base

  self:
    path: zephyr-spi-target-demo 
